name: echomimi
description: ECHOMIMI - Tu mascota virtual de seguridad digital

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.0
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.0.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.0
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/echomimi/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
